export const services = ["Plumbing",
  "Electrical",
  "Painting & Decorating",
  "Cleaning Services",
  "Tree Services",
  "Garden Design",
  "Massage Therapy",
  "Event Planning",
  "Personal Trainer",
  "Photography",
  "Doctors",
  "Pet Walking"];
  
export const counties = [
  "Carlow",
  "Cavan",
  "Clare",
  "Cork",
  "Donegal",
  "Dublin",
  "Galway",
  "Kerry",
  "Kildare",
  "Kilkenny",
  "Laois",
  "Leitrim",
  "Limerick",
  "Longford",
  "Mayo",
  "Meath",
  "Monaghan",
  "Offaly",
  "Roscommon",
  "Sligo",
  "Tipperary",
  "Waterford",
  "Westmeath",
  "Wexford",
  "Wicklow",
]
export const times = ["12", "01", "02", "03", "04", "05", "06", "07", "08", "09", '10', '11']
export const job_prefered_days = ["Flexible", "Sunday", "Monday", "Tuesday", "Wednesday", 'Thursday', "Friday", "Saturday"]